language: ruby

rvm:
 - 2.7.1

nodejs:
 - 12.18.3

services:
 - postgresql

before_script:
 - cp config/database.yml.travis config/database.yml
 - psql -c 'create database travis_ci_test;' -U postgres

script:
 - bundle update --bundler
 - bundle exec rake db:migrate
 - bundle exec rspec spec
 - bundle exec cucumber